<?php

namespace SO\PlatformBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;

/**
 * PropositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropositionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllBySondage($sondage_id) {
        $qb = $this->createQueryBuilder('proposition')
        ->innerJoin('proposition.sondage', 'sondage')
        ->where('sondage.id = :sondage_id')
        ->setParameter('sondage_id', $sondage_id);

        return $qb->getQuery()->getResult();
    }

    public function findById($id) {
        $qb = $this->createQueryBuilder('proposition')
        ->where('proposition.id = :id')
        ->setParameter('id', $id);
        return $qb->getQuery()->getResult();

    }

}
