<?php

namespace SO\PlatformBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;

/**
 * SondageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SondageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByUser($user_id) {
        $qb = $this->createQueryBuilder('sondage')
        ->innerJoin('sondage.user', 'user')
        ->where('user.id = :user_id')
        ->orderBy('sondage.id', 'DESC')
        ->setParameter('user_id', $user_id);

        return $qb->getQuery()->getResult();
    }

    public function findOneById($id) {
        $qb = $this->createQueryBuilder('sondage')
        ->where('sondage.id = :id')
        ->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }
}
